Server:
  port: "9001"
  # release / debug / test
  mode: "debug"

DataBase:
  # 数据库类型 mysql sqlite3
  driver: sqlite3
  # 数据库连接sqlite3数据文件的路径
  source: data/watchalert.db

MySQL:
  host: w8t-mysql
  port: 3306
  user: root
  pass: w8t.123
  dbName: watchalert
  timeout: 10s

Redis:
  host: w8t-redis
  port: 6379
  pass: ""

Jwt:
  # 失效时间
  expire: 18000

Ldap:
  enabled: false
  # LDAP 服务地址
  address: "192.168.1.100:399"
  # 基础 DN
  baseDN: "dc=test,dc=com"
  # admin DN
  adminUser: "cn=admin,dc=test,dc=com"
  # admin 密码
  adminPass: "test123."
  # 用户 DN
  userDN: "ou=people,dc=test,dc=com"
  # 用户 DN 前缀
  userPrefix: "uid"
  # 默认用户角色
  defaultUserRole: "ur-cq7nkj1d6gviooaigqi0"
  # 定时任务，用于同步 LDAP 用户到W8T
  cronjob: "*/1 * * * *"
